#!/usr/bin/env bash
# Moves a file from Holberton's client system to a different server.
# Requires four parameters:
#+     Path of the file to transfer.
#+     IP address of the destination server.
#+     Username for scp connection.
#+     Location of the SSH private key for scp.

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
