#!/usr/bin/env bash
# Sets up nginx and arranges its configuration on a distant server

apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "Hello World!"