#!/usr/bin/env bash
# Sets up nginx and arranges its configuration on a distant server

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart
