#!/usr/bin/env bash
# Installs, configures, and starts the server

apt-get -y update
apt-get -y install nginx
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a \\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
