#!/usr/bin/env bash
# Installs, configures, and starts the server

apt-get -y update
apt-get -y install nginx
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/a \ \ \ \ \ \ \ \ location /redirect_me {\n\ \ \ \ \ \ \ \ \ \ \ \ rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\ \ \ \ \ \ \ \ }' /etc/nginx/sites-available/default
service nginx restart
