#!/usr/bin/env bash
# This script creates a PID file, handles signals, and deletes the PID file upon termination
PID_FILE="/var/run/myscript.pid"
# Create PID file
echo $$ > "$PID_FILE"
# Define signal handlers
handle_sigterm_quit() {
    echo "I hate the kill command"
    rm -f "$PID_FILE"
    exit
}
trap 'echo "Y U no love me?!"' SIGINT
trap handle_sigterm_quit SIGTERM SIGQUIT
# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
