#!/usr/bin/env bash
# This script loops from 1 to 10, displaying specific messages for the 4th and 8th iterations, and 'Best School' otherwise.
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i+1))
done
