#!/usr/bin/env bash
# This script displays the part of the filename after the first dash for each non-hidden file in the current directory.
for file in *
do
    if [[ $file == *-* && $file != .* ]]; then
        echo "${file#*-}"
    fi
done
