#!/usr/bin/env bash
# This script modifies:
#   - /etc/hosts to map localhost to 127.0.0.2 
#   - facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.backup
echo "127.0.0.2		localhost" > ~/hosts.backup
echo "8.8.8.8		facebook.com" >> ~/hosts.backup
cp -f ~/hosts.backup /etc/hosts
